using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using MintPlayer.SourceGenerators.Tests._Infrastructure;

namespace MintPlayer.SourceGenerators.Tests.Guards;

/// <summary>
/// PRD-ValueComparerGenerator-DownstreamFindings D4: no generated file raises CS1591 in a consumer that builds with
/// <c>GenerateDocumentationFile</c>.
/// </summary>
/// <remarks>
/// <para>
/// A consumer cannot fix a CS1591 in generated code. The <c>&lt;auto-generated&gt;</c> header doesn't suppress it, an
/// <c>.editorconfig</c> severity isn't applied to generated files, and <c>[assembly: SuppressMessage]</c> doesn't
/// suppress compiler warnings. MintPlayer.AspNetCore.Tools had to write a <c>DiagnosticSuppressor</c> for 12.0.1's
/// public, empty <c>IncrementalValueProviderAdditionalEx</c> and for the undocumented members of
/// <c>GeneratedEquality.g.cs</c> (#187).
/// </para>
/// <para>
/// Each generator runs over its <see cref="FixedFileSetGuardTests"/> corpus, whose inputs are public. The compilation
/// is then reparsed with <see cref="DocumentationMode.Diagnose"/>, which is what <c>GenerateDocumentationFile</c> sets,
/// and only CS1591s located in generated trees count. The corpus's own undocumented types are the consumer's business.
/// </para>
/// </remarks>
public class DocumentedOutputGuardTests
{
    public static TheoryData<FixedFileSetGuardTests.Case> AllCases()
    {
        var data = new TheoryData<FixedFileSetGuardTests.Case>();
        foreach (var c in FixedFileSetGuardTests.Cases) data.Add(c);
        return data;
    }

    [Theory]
    [MemberData(nameof(AllCases))]
    public void EveryGenerator_EmitsNoMissingDocumentationWarning(FixedFileSetGuardTests.Case c)
    {
        var run = FixedFileSetGuardTests.Run(c, 2);
        run.GeneratedSources.Should().NotBeEmpty($"the {c.Generator} corpus must make the generator emit something");

        var warnings = MissingDocumentationInGeneratedCode(run);

        warnings.Should().BeEmpty(
            $"{c.Generator} must not make a consumer with GenerateDocumentationFile warn CS1591; the consumer can't "
            + $"document or suppress generated code:{Environment.NewLine}{string.Join(Environment.NewLine, warnings)}");
    }

    /// <summary>
    /// The guard's negative control: a generator that emits an undocumented public type must fail it. Without this, a
    /// guard that reparsed nothing, or filtered out every tree, would pass forever.
    /// </summary>
    [Fact]
    public void TheGuard_DetectsAnUndocumentedPublicMember()
    {
        var run = GeneratorHarness.Run(
            nameof(UndocumentedPublicTypeGenerator),
            ["namespace Demo;"],
            generatorAssemblyName: typeof(UndocumentedPublicTypeGenerator).Assembly.GetName().Name!);

        MissingDocumentationInGeneratedCode(run).Should().ContainSingle()
            .Which.Should().Contain("'Undocumented'");
    }

    private static List<string> MissingDocumentationInGeneratedCode(GeneratorRun run)
    {
        var generated = run.GeneratedSources.Select(s => s.HintName).ToHashSet(StringComparer.Ordinal);
        var compilation = run.UpdatedCompilation;

        var reparsed = compilation.SyntaxTrees.Select(tree => CSharpSyntaxTree.ParseText(
            tree.GetText(),
            ((CSharpParseOptions)tree.Options).WithDocumentationMode(DocumentationMode.Diagnose),
            tree.FilePath));

        return compilation.RemoveAllSyntaxTrees().AddSyntaxTrees(reparsed)
            .GetDiagnostics()
            .Where(d => d.Id == "CS1591")
            .Where(d => d.Location.SourceTree is { } tree && generated.Contains(Path.GetFileName(tree.FilePath)))
            .Select(d => d.ToString())
            .Distinct(StringComparer.Ordinal)
            .ToList();
    }
}

/// <summary>The shape the guard forbids. Only <see cref="DocumentedOutputGuardTests"/> runs it.</summary>
public sealed class UndocumentedPublicTypeGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
        => context.RegisterPostInitializationOutput(static ctx =>
            ctx.AddSource("Undocumented.g.cs", "// <auto-generated/>\nnamespace Demo { public class Undocumented { } }"));
}
