using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace MintPlayer.Assertions.SourceGenerator.Tests.Generators;

/// <summary>
/// No generated file raises CS1591 in a consumer that builds with <c>GenerateDocumentationFile</c>.
/// </summary>
/// <remarks>
/// The counterpart of <c>MintPlayer.SourceGenerators.Tests.Guards.DocumentedOutputGuardTests</c> for the generators
/// that ship inside MintPlayer.Assertions (PRD-ValueComparerGenerator-DownstreamFindings D4). A consumer can neither
/// document nor suppress a CS1591 in generated code. Each generator runs over its <see cref="FixedFileSetGuardTests"/>
/// corpus; the compilation is reparsed with <see cref="DocumentationMode.Diagnose"/>, which is what
/// <c>GenerateDocumentationFile</c> sets, and only CS1591s located in generated trees count.
/// </remarks>
public class DocumentedOutputGuardTests
{
    public static TheoryData<FixedFileSetGuardTests.Case> AllCases()
    {
        var data = new TheoryData<FixedFileSetGuardTests.Case>();
        foreach (var c in FixedFileSetGuardTests.Cases) data.Add(c);
        return data;
    }

    [Theory]
    [MemberData(nameof(AllCases))]
    public void EveryGenerator_EmitsNoMissingDocumentationWarning(FixedFileSetGuardTests.Case c)
    {
        var run = Harness.Instance.RunGenerator(c.Generator, c.Corpus(2));
        run.GeneratedSources.Should().NotBeEmpty($"the {c.Generator} corpus must make the generator emit something");

        var warnings = MissingDocumentationInGeneratedCode(run);

        warnings.Should().BeEmpty(
            $"{c.Generator} must not make a consumer with GenerateDocumentationFile warn CS1591; the consumer can't "
            + $"document or suppress generated code:{Environment.NewLine}{string.Join(Environment.NewLine, warnings)}");
    }

    /// <summary>
    /// The guard's negative control: a generator that emits an undocumented public type must fail it. Without this, a
    /// guard that reparsed nothing, or filtered out every tree, would pass forever.
    /// </summary>
    [Fact]
    public void TheGuard_DetectsAnUndocumentedPublicMember()
    {
        var run = GeneratorHarness.ForAssembly(typeof(UndocumentedPublicTypeGenerator).Assembly.GetName().Name!)
            .RunGenerator(nameof(UndocumentedPublicTypeGenerator), "namespace Demo;");

        MissingDocumentationInGeneratedCode(run).Should().ContainSingle()
            .Which.Should().Contain("CS1591").And.Contain("'Undocumented'");
    }

    private static List<string> MissingDocumentationInGeneratedCode(GeneratorResult run)
    {
        var generated = run.GeneratedSources.Select(s => s.HintName).ToHashSet(StringComparer.Ordinal);
        var compilation = run.UpdatedCompilation;

        var reparsed = compilation.SyntaxTrees.Select(tree => CSharpSyntaxTree.ParseText(
            tree.GetText(),
            ((CSharpParseOptions)tree.Options).WithDocumentationMode(DocumentationMode.Diagnose),
            tree.FilePath));

        return compilation.RemoveAllSyntaxTrees().AddSyntaxTrees(reparsed)
            .GetDiagnostics()
            .Where(d => d.Id == "CS1591")
            .Where(d => d.Location.SourceTree is { } tree && generated.Contains(Path.GetFileName(tree.FilePath)))
            .Select(d => d.ToString())
            .Distinct(StringComparer.Ordinal)
            .ToList();
    }
}

/// <summary>The shape the guard forbids. Only <see cref="DocumentedOutputGuardTests"/> runs it.</summary>
public sealed class UndocumentedPublicTypeGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
        => context.RegisterPostInitializationOutput(static ctx =>
            ctx.AddSource("Undocumented.g.cs", "// <auto-generated/>\nnamespace Demo { public class Undocumented { } }"));
}
