using MintPlayer.SourceGenerators.Tools;
using MintPlayer.ValueComparerGenerator.Attributes;

namespace MintPlayer.Assertions.SourceGenerator.Models;

/// <summary>Which assertions class the generated extension method hangs off.</summary>
public enum SubjectKind
{
    Object,
    String,
    Boolean,
    Numeric,
}

/// <summary>One extra parameter of the user's predicate, forwarded to the generated assertion.</summary>
/// <remarks>Value equality is generated by <c>[GenerateEquality]</c>.</remarks>
[GenerateEquality]
public sealed partial class ParameterDeclaration
{
    public ParameterDeclaration(string name, string typeFullName)
    {
        Name = name;
        TypeFullName = typeFullName;
    }

    public string Name { get; }
    public string TypeFullName { get; }
}

/// <summary>
/// A <c>[GenerateAssertion]</c> predicate reduced to everything the emitter needs, plus the
/// reason it was rejected when the shape is unsupported (in which case only
/// <see cref="Diagnostic"/> and <see cref="Location"/> are meaningful).
/// </summary>
/// <remarks>
/// Value equality is generated by <c>[GenerateEquality]</c>. Every property takes part,
/// <see cref="Location"/> included: the model carries the MPAG001 location, so a predicate that
/// only moved must still re-run the step that reports it.
/// </remarks>
[GenerateEquality]
public sealed partial class AssertionMethodDeclaration
{
    public string Namespace { get; set; } = string.Empty;

    /// <summary>Simple name of the class declaring the predicate (nested classes joined with '_').</summary>
    public string ContainingTypeName { get; set; } = string.Empty;

    /// <summary>Fully qualified (global::) name of the class declaring the predicate.</summary>
    public string ContainingTypeFullName { get; set; } = string.Empty;

    public string MethodName { get; set; } = string.Empty;

    /// <summary>Name of the generated fluent assertion (from the attribute, or derived).</summary>
    public string GeneratedName { get; set; } = string.Empty;

    /// <summary>The generated name humanized for the failure message, e.g. "be even".</summary>
    public string Phrase { get; set; } = string.Empty;

    public SubjectKind SubjectKind { get; set; }

    /// <summary>Fully qualified subject type; for numerics the non-nullable underlying type.</summary>
    public string SubjectTypeFullName { get; set; } = string.Empty;

    public EquatableArray<ParameterDeclaration> ExtraParameters { get; set; } = EquatableArray<ParameterDeclaration>.Empty;

    /// <summary>
    /// False when the predicate's class or one of its parameter types is not public — the
    /// generated extension class then has to be internal to keep accessibility consistent.
    /// </summary>
    public bool IsPublic { get; set; }

    /// <summary>Set when the method shape is unsupported; the emitter skips it and MPAG001 is reported.</summary>
    public string? Diagnostic { get; set; }

    public LocationKey? Location { get; set; }

    public override string ToString() => $"{ContainingTypeFullName}.{MethodName}";
}
