using MintPlayer.SourceGenerators.Tools;
using MintPlayer.ValueComparerGenerator.Attributes;

namespace MintPlayer.Assertions.SourceGenerator.Models;

/// <summary>A type for which reflection-free equivalency accessors must be registered.</summary>
/// <remarks>Value equality is generated by <c>[GenerateEquality]</c>.</remarks>
[GenerateEquality]
public sealed partial class EquivalencyTypeDeclaration
{
    public EquivalencyTypeDeclaration(string typeFullName, EquatableArray<MemberDeclaration> members, bool extendedMembersComplete = true)
    {
        TypeFullName = typeFullName;
        Members = members;
        ExtendedMembersComplete = extendedMembersComplete;
    }

    /// <summary>Fully qualified (global::) name of the type.</summary>
    public string TypeFullName { get; }

    public EquatableArray<MemberDeclaration> Members { get; }

    /// <summary>
    /// False when a member excluded by default was skipped because generated code cannot reference
    /// it — an <c>internal</c> member of a type in another assembly with no
    /// <c>InternalsVisibleTo</c>. The runtime then refuses the generated table for any option that
    /// wants those members and falls back to reflection, rather than silently comparing fewer of
    /// them than the same option would compare for a type in this assembly.
    /// </summary>
    public bool ExtendedMembersComplete { get; }

    public override string ToString() => TypeFullName;
}
