tls:
  options:
    mtls:
      minVersion: VersionTLS12
      maxVersion: VersionTLS12
      alpnProtocols:
        - http/1.1
      clientAuth:
        clientAuthType: RequestClientCert
        caFiles:
          - /etc/traefik/dynamic/belgium-root-ca4.pem
          - /etc/traefik/dynamic/citizen-ca.pem
