using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.CodeDom.Compiler;
using System.Text;

namespace MintPlayer.SourceGenerators.Tools;

public abstract class Producer
{
    /// <summary>
    /// Used when the host supplies no <c>build_property.rootnamespace</c>.
    /// </summary>
    /// <remarks>
    /// Six producers across four generator projects write <c>namespace {RootNamespace}</c>
    /// unguarded. With a null or empty value that emitted a bare <c>namespace</c> — CS1001,
    /// "Identifier expected" — so the generator silently broke the consumer's build. MSBuild
    /// always sets RootNamespace, which is why it never showed in a normal build; it bites
    /// any other host, including a plain CSharpGeneratorDriver. Normalizing here fixes every
    /// producer at once, including ones written later.
    /// </remarks>
    public const string DefaultRootNamespace = "GeneratedCode";

    protected Producer(string rootNamespace, string filename)
    {
        RootNamespace = string.IsNullOrWhiteSpace(rootNamespace) ? DefaultRootNamespace : rootNamespace;
        Filename = filename;
    }

    public const string Header = """
        //-----------------------------------------------------------------------------------//
        // <auto-generated>                                                                  //
        //    This code was generated from source generator.                                 //
        //                                                                                   //
        //    Manual changes to this file may cause unexpected behavior in your application. //
        //    Manual changes to this file will be overwritten if the code is regenerated.    //
        // </auto-generated>                                                                 //
        //-----------------------------------------------------------------------------------//
        """;

    public string RootNamespace { get; }
    public string Filename { get; }

    protected abstract void ProduceSource(IndentedTextWriter writer, CancellationToken cancellationToken);

    public void Produce(SourceProductionContext context, Compilation compilation)
    {
        context.CancellationToken.ThrowIfCancellationRequested();
        if (string.IsNullOrEmpty(Filename)) return;

        using var textWriter = new StringWriter();
        using var writer = new IndentedTextWriter(textWriter);

        try
        {
            ProduceSource(writer, context.CancellationToken);

            var code = textWriter.ToString();
            if (!string.IsNullOrEmpty(code))
                context.AddSource(Filename, SourceText.From(code, Encoding.UTF8));
        }
        catch (OperationCanceledException)
        {
            // Cancellation is not a failure; let the driver handle it.
            throw;
        }
        catch (System.Exception ex)
        {
            // This used to be `catch (System.Exception) { }`. A generator that threw
            // produced no file AND no diagnostic, so the consumer got a silent miscompile —
            // missing generated members with nothing anywhere to explain why. Reporting it
            // keeps the build alive (an unhandled exception here would take the whole
            // compilation down) while making the failure visible.
            context.ReportDiagnostic(Diagnostic.Create(ProducerFailed, Location.None, Filename, ex.GetType().Name, ex.Message));
        }
    }

    /// <summary>
    /// Reported when <see cref="ProduceSource"/> throws. Deliberately an error: a generator
    /// that cannot produce its file has broken the consumer's build in a way that is very
    /// hard to diagnose from the symptoms alone.
    /// </summary>
    public static readonly DiagnosticDescriptor ProducerFailed = new(
        id: "MPSG001",
        title: "Source generator failed to produce a file",
        messageFormat: "The source generator failed while producing '{0}': {1}: {2}",
        category: "MintPlayer.SourceGenerators",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);
}