using System;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Spike.S3.Generator
{
    [Generator(LanguageNames.CSharp)]
    public sealed class InterceptorGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var sites = context.SyntaxProvider
                .CreateSyntaxProvider(
                    static (node, _) => node is InvocationExpressionSyntax
                    {
                        Expression: MemberAccessExpressionSyntax { Name.Identifier.ValueText: "ExecuteAsync" },
                        ArgumentList.Arguments.Count: 2,
                    },
                    static (ctx, ct) => SiteAnalyzer.Analyze(ctx, ct))
                .Where(static m => m is not null)
                .Select(static (m, _) => m!)
                .WithTrackingName("Sites");

            var all = sites.Collect()
                .Select(static (a, _) => new EquatableArray<SiteModel>(a))
                .WithTrackingName("AllSites");

            var probe = context.AnalyzerConfigOptionsProvider
                .Select(static (o, _) => o.GlobalOptions.TryGetValue("build_property.S3MismatchProbe", out var v)
                                         && string.Equals(v, "true", StringComparison.OrdinalIgnoreCase));

            context.RegisterSourceOutput(all.Combine(probe), static (spc, pair) =>
                spc.AddSource("S3.Interceptors.g.cs", Emit(pair.Left, pair.Right)));
        }

        private static string Lit(string s) => SymbolDisplay.FormatLiteral(s, quote: true);

        private static string Emit(EquatableArray<SiteModel> sites, bool mismatchProbe)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("namespace System.Runtime.CompilerServices");
            sb.AppendLine("{");
            sb.AppendLine("    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]");
            // Not a primary constructor: CS9113 (unread parameter) is reported even in <auto-generated/> code.
            sb.AppendLine("    file sealed class InterceptsLocationAttribute : global::System.Attribute");
            sb.AppendLine("    {");
            sb.AppendLine("        public InterceptsLocationAttribute(int version, string data) { _ = version; _ = data; }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();
            sb.AppendLine("namespace Spike.S3.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    file static class PipelineInterceptors");
            sb.AppendLine("    {");

            var lowered = sites.Where(s => s.Outcome == Outcomes.Lowered).ToList();
            if (lowered.Count > 0)
            {
                // What an interceptor CAN do: replace the call target. What it CANNOT do: change how the
                // arguments were evaluated. The lambda has already been converted to a
                // Func<CancellationToken, ValueTask<T>> (display class + delegate allocated) in the caller
                // before this method runs, and the captured values are only reachable through that delegate.
                // So the only thing left to "lower" to is the state overload with the delegate as state.
                foreach (var s in mismatchProbe ? lowered.Skip(1) : lowered)
                {
                    sb.AppendLine($"        // {s.Site} @ {s.DisplayLocation}");
                    sb.AppendLine($"        [global::System.Runtime.CompilerServices.InterceptsLocation({s.LocationVersion}, {Lit(s.LocationData)})]");
                }
                sb.AppendLine("        public static global::System.Threading.Tasks.ValueTask<T> ExecuteAsync<T>(");
                sb.AppendLine("            global::System.Func<global::System.Threading.CancellationToken, global::System.Threading.Tasks.ValueTask<T>> callback,");
                sb.AppendLine("            global::System.Threading.CancellationToken cancellationToken)");
                sb.AppendLine("        {");
                sb.AppendLine("            global::Spike.S3.Pipeline.Intercepted++;");
                sb.AppendLine("            return global::Spike.S3.Pipeline.ExecuteAsync(static (cb, c) => cb(c), callback, cancellationToken);");
                sb.AppendLine("        }");
            }

            if (mismatchProbe && lowered.Count > 0)
            {
                // Probe: an interceptor whose callback parameter is NOT the original delegate type. If the
                // compiler accepted this, the lambda could bind to a different (state-taking) type.
                var s = lowered[0];
                sb.AppendLine();
                sb.AppendLine($"        [global::System.Runtime.CompilerServices.InterceptsLocation({s.LocationVersion}, {Lit(s.LocationData)})]");
                sb.AppendLine("        public static global::System.Threading.Tasks.ValueTask<T> Probe<T>(");
                sb.AppendLine("            global::System.Func<object?, global::System.Threading.CancellationToken, global::System.Threading.Tasks.ValueTask<T>> callback,");
                sb.AppendLine("            global::System.Threading.CancellationToken cancellationToken) => default;");
            }

            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    public static class S3SiteReport");
            sb.AppendLine("    {");
            sb.AppendLine("        public static readonly (string Site, string Location, string Outcome, string Detail, string Rewrite)[] Sites =");
            sb.AppendLine("        {");
            foreach (var s in sites.OrderBy(s => s.DisplayLocation, StringComparer.Ordinal))
                sb.AppendLine($"            ({Lit(s.Site)}, {Lit(s.DisplayLocation)}, {Lit(s.Outcome)}, {Lit(s.Detail)}, {Lit(s.Rewrite)}),");
            sb.AppendLine("        };");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }
    }
}
